spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: f445effa904c57a1b9c645c22d84cd16
kakao:
  authorization-uri: https://kauth.kakao.com/oauth/authorize
  redirect-uri: http://localhost:8080/auth/kakao/callback
  client-id: f445effa904c57a1b9c645c22d84cd16
  response-type: code
custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUserOauthId: 'oauthId'

# Jwt SecretKey
jwt:
  secretKey: 12h7hd791h1293j9jk3e9j1238ej1293e8j213e